"""make task due_date non-nullable

Revision ID: 27adb1d43b50
Revises: 06fc524dd3e2
Create Date: 2026-10-01 11:36:42.927939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27adb1d43b50'
down_revision = '06fc524dd3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
